name: Update README with Latest Posts

on:
  schedule:
    # 매일 03:00 KST(=18:00 UTC)에 실행
    - cron: '0 18 * * *'
  workflow_dispatch:

permissions:           # ✅ README에 쓰기 권한 필수
  contents: write

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          readme_path: README.md
          max_post_count: 5
          feed_list: "https://jae-choi.github.io/news/feed.xml"
          template: |
            * **<a href="{{url}}" target="_blank">{{title}}</a>**  
              _{{description}}_
          comment_tag_name: posts
          commit_message: "docs: 최신 글 자동 반영"

