name: Update README with Latest Posts

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure posts markers exist in README
        run: |
          if ! grep -q "<!-- posts:START -->" README.md; then
            printf '\n## Latest posts\n<!-- posts:START -->\n<!-- posts:END -->\n' >> README.md
          fi

      - name: Update README with latest posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          readme_path: README.md
          max_post_count: 1
          feed_list: "https://jae-choi.github.io/news/feed.xml"
          accept_header: "application/atom+xml"
          # 핵심: Atom <summary>를 템플릿 변수 $summary로 노출
          custom_tags: "summary/summary/"
          template: "* [$title]($url) _$summary_"
          comment_tag_name: "posts"
          commit_message: "docs: 최신 글 자동 반영"
          # 엔티티 이중 인코딩 방지
          disable_html_encoding: true
