name: Update README with Latest Posts

on:
  schedule:
    - cron: '0 18 * * *'  # 매일 03:00 KST (UTC 18:00)
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # README에 섹션/마커 없으면 생성 (HTML로 고정 렌더)
      - name: Ensure posts section exists
        run: |
          if ! grep -q "<!-- posts:START -->" README.md; then
            printf '\n## Latest posts\n<ul>\n<!-- posts:START -->\n<!-- posts:END -->\n</ul>\n' >> README.md
          fi

      - name: Update README with latest posts (summary only)
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          readme_path: "README.md"
          comment_tag_name: "posts"                       # README의 마커와 일치
          feed_list: "https://jae-choi.github.io/news/feed.xml"
          accept_header: "application/atom+xml"           # Atom 피드
          custom_tags: "summary/summary/"                 # <summary> => $summary
          template: '<li><a href="$url">$title</a> — <em>$summary</em></li>'
          max_post_count: 1
          disable_html_encoding: true
          description_max_length: 160
          item_exec: |                                    # summary 정제
            const decode = s => s ? s.replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&') : '';
            const strip  = s => s ? s.replace(/<[^>]+>/g,'').replace(/\s+/g,' ').trim() : '';
            if (post.summary) post.summary = strip(decode(post.summary));
            if (!post.summary) post.summary = '';

      - name: Show updated README (first 120 lines)
        if: ${{ always() }}
        run: sed -n '1,120p' README.md
