name: Update README with Latest Posts

on:
  schedule:
    - cron: '0 18 * * *'        # 매일 03:00 KST
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          readme_path: README.md
          max_post_count: 5
          feed_list: "https://jae-choi.github.io/news/feed.xml"
          template: "* [{{title}}]({{url}})  _{{description}}_"   # ← 한 줄!
          comment_tag_name: posts
          commit_message: "docs: 최신 글 자동 반영"
