name: Update README with Latest Posts

on:
  # 매일 03:00 KST (UTC 18:00)에 실행 + 수동 트리거
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
      # 1) 레포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) 피드 정상 응답·본문 확인 (디버깅용)
      - name: "Debug: show feed contents"
        run: |
          curl -fsSL https://jae-choi.github.io/news/feed.xml | head -n 20

      # 3) README 최신 글 자동 삽입
      - name: Update README with latest posts
        uses: gautamkrishnar/blog-post-workflow@v1.8.6   # ✅ 최신 태그
        with:
          readme_path: README.md
          max_post_count: 1
          feed_list: https://jae-choi.github.io/news/feed.xml   # Atom 피드
          template: '* [{{title}}]({{url}}) _{{description}}_'  # 공백 정리
          comment_tag_name: posts
          commit_message: 'docs: 최신 글 자동 반영'

      # 4) 결과 확인용 출력
      - name: Show updated README
        if: always()
        run: |
          sed -n '1,30p' README.md
