name: Update README with Latest Posts

on:
  schedule:
    - cron: '0 18 * * *'        # 매일 03:00 KST (UTC 18:00)
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
      # 1) 레포지터리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) 피드 응답 디버그
      - name: "Debug: show feed contents"
        run: |
          curl -fsSL https://jae-choi.github.io/news/feed.xml | head -n 20

      # 3) README 최신 글 삽입
      - name: Update README with latest posts
        uses: gautamkrishnar/blog-post-workflow@1.9.3   # 또는 @v1
        with:
          readme_path: README.md
          max_post_count: 1
          feed_list: https://jae-choi.github.io/news/feed.xml
          template: '* [$title]($url) _$description_'
          comment_tag_name: posts
          commit_message: 'docs: 최신 글 자동 반영'

      # 4) 결과 확인
      - name: Show updated README
        if: always()
        run: |
          sed -n '1,30p' README.md
