name: Update README with Latest Posts

on:
  schedule:
    - cron: '0 18 * * *'        # 매일 03:00 KST (UTC 18:00)
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # README에 마커 없으면 자동 삽입 (한번만 실행됨)
      - name: Ensure posts markers exist in README
        run: |
          if ! grep -q "<!-- posts:START -->" README.md; then
            cat >> README.md <<'EOF'

## Latest posts
<!-- posts:START -->
<!-- posts:END -->
EOF
          fi

      - name: "Debug: show feed contents"
        run: |
          echo "== headers ==" && curl -fsSI https://jae-choi.github.io/news/feed.xml | sed -n '1,15p'
          echo "== body (first 20 lines) ==" && curl -fsSL https://jae-choi.github.io/news/feed.xml | head -n 20

      - name: Update README with latest posts
        uses: gautamkrishnar/blog-post-workflow@1.9.3
        with:
          readme_path: README.md
          max_post_count: 1
          feed_list: https://jae-choi.github.io/news/feed.xml
          # ✅ YAML에서 *가 앵커로 오인되지 않도록 반드시 따옴표
          template: "* [$title]($url) _$description_"
          comment_tag_name: posts
          commit_message: "docs: 최신 글 자동 반영"
          description_max_length: 160
          # ✅ Atom <summary> → description 복사 + HTML 디코드 + 태그 제거
          item_exec: |
            const decode = s => s?.replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&');
            const strip  = s => s?.replace(/<[^>]+>/g,'').trim();
            const src = post.summary || post.description;
            post.description = strip(decode(src));
          # 필요시 그대로 두세요
          disable_html_encoding: false

      - name: Show updated README
        if: ${{ always() }}
        run: sed -n '1,30p' README.md
